spring:
    datasource:
        url: jdbc:mariadb://textmining-server-db.cfjjncxgjjam.ap-northeast-1.rds.amazonaws.com:3306/aws
        username: root
        password: Chlgurtns98!

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true